# 异步代码的测试方法

## 异步代码测试失败举例

`fetchData.js`:

```js
import axios from 'axios';
export const fetchData = ()=>{
    axios.get('http:www.dell-lee.com/react/api/demo.json').then((res)=>{
        fn(res.data)
    })
   /* 
     {
      "success": true
     }
    */
    //或
     //axios.get('http:www.dell-lee.com/react/api/demo1.json').then((res)=>{
      //  fn(res.data)
    //})
    //404 NOT FOUND
}
```



`fetchData.test.js`

```js
import {fetchData} from './fetchData';
test('fetchData 返回结果为 {success: true}',()=>{
    fetchData((data)=>{
        expect(data).toEqual({
            success: true
        })
    })
})
```

因为异步的原因，上述的测试用例代码并不会执行。而是会跳过这段代码执行，默认测试用例通过。但这显然是不行的，那么如何解决这中异步的原因呢？

## 解决方法

栗子：
demo.js

```js
export const fetchData = ()=>{
    axios.get('http://www.dell-lee.com/react/api/demo.json').then((res)=>{
        fn(res.data)
    })
}
```

demo.test.js
```js
//未请求到数据，因为expect那儿直接跳过执行了，所以此时测试用例会通过。
describe('异步测试',function(){
  it('axios是否请求到数据 {success:true}',function(){
    fetchData(function(data){
      expect(data).to.equal({success:true})
    })
  })
})
```
在mocha中使用回调函数的风格对异步处理进行测试。

### 方法1：回调函数：

demo.test.js
```js
describe('异步测试',function(){
  it('axios是否请求到数据 {success:true}',function(done){
    fetchData((data)=>{
      // console.log(data)
      expect(data).to.eql({success:true});
      done();
    })
  })
})
```
### 方法2：async await

demo.js需要返回一个promise对象

```js
export const fetchData = ()=>{
    return axios.get('http://www.dell-lee.com/react/api/demo.json')
}
```

demo.test.js
```js
describe('异步测试',function(){
  it('axios是否请求到数据 {success:true}',async function(){
    // console.log(await fetchData())
    const res = await fetchData()
    expect(res.data).to.eql({success:true})
  })
})
```

### 方法3：Promise

demo.js同样也需要返回一个promise对象。

demo.test.js
```js
describe('异步测试',function(){
  it('axios是否请求到数据 {success:true}',function(done){
    fetchData().then((res)=>
      expect(res.data).to.eql({success:true});
    }).then(done,done)
  })
})
```

